services:
  analysis-env:
    image: tyjnico/portugal_white_wine_quality_predictor_py:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 10G
    platform: linux/amd64